## Crear X, Y

In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv('data/calor - Plant_1_Weather_Sensor_Data.csv', delimiter='\t', header=0 ,dtype=np.float64)
data = data.values

set_x = data[:,0:-1]
set_y = data[:,-1]

print(set_x)
print(set_y)


## Normalizar X, Y

In [80]:
def norm(arr):
    mean = np.mean(arr,axis=0)
    std = np.std(arr, axis=0)
    for i in range(0, arr.shape[0]):
        arr[i] = np.true_divide(arr[i] - mean, std)
    return arr

set_x = norm(set_x)
set_y = norm(set_y)
print(set_x)
print(set_y)

[[ 1.4154413  -1.18184136 -1.03892124 -0.8259031 ]
 [ 1.4154413  -0.26396904 -1.24905478  0.03036408]
 [ 1.4154413  -0.66388654 -1.1518029   0.17611169]
 [-0.17892312  1.10667332 -0.93038119 -0.7530293 ]
 [ 0.35253169  0.27688855 -1.48610625 -0.47975254]
 [ 2.47835091  1.93821984 -1.22503125  0.01214563]
 [ 0.35253169  1.89769956  1.82422057 -2.17406847]
 [ 0.35253169  1.5576816  -0.99203194 -0.31578648]
 [ 0.35253169  0.3614526   0.87167309 -0.7530293 ]
 [-0.71037792  0.47596642  0.85141228 -0.33400493]
 [ 0.35253169  0.26279454  0.10813001 -0.73481085]
 [-0.17892312  1.5576816   2.4951428  -0.8259031 ]
 [-0.71037792  1.01330051  0.39496518  0.06680099]
 [-0.71037792 -0.06136766  0.29366114 -0.46153409]
 [-0.71037792  0.15885122  0.75068711  0.68622832]
 [-0.71037792  0.13418671  1.38195604  0.2854224 ]
 [-0.71037792 -0.06312941  0.85170172  0.03036408]
 [-0.71037792 -0.92286395 -0.24325031 -0.55262634]
 [-0.71037792  0.83536365  0.10118345  2.79956861]
 [ 0.88398649  0.17470698  0.12

## Dividir en train, test

In [81]:
limit = int(0.7*len(set_x))
train_x , test_x = set_x[:limit,:], set_x[limit:, :]
train_y , test_y = set_y[:limit], set_y[limit:] 

np.savetxt('data/1_train_x.csv', train_x, delimiter=',')
np.savetxt('data/1_train_y.csv', train_y, delimiter=',')

np.savetxt('data/1_test_x.csv', test_x, delimiter=',')
np.savetxt('data/1_test_y.csv', test_y, delimiter=',')


In [71]:
limit = int(len(array1)*0.7)
array1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
array2 = np.array([1,2,3,4,5,6])
trainx , testx = array1[:limit,:], array1[limit:, :]
trainy , testy = array2[:limit], array2[limit:]
print(trainx)
print(testx)
print(trainy)
print(testy)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]
[1 2 3 4]
[5 6]
